package com.exsample.entity;
// Generated 2019/10/14 14:23:33 by Hibernate Tools 5.4.3.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.ArrayList;
import java.util.HashSet;

import javax.persistence.Entity;
import javax.persistence.EmbeddedId;
import javax.persistence.Table;
import javax.persistence.IdClass;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.OneToMany;
import javax.persistence.FetchType;
import javax.persistence.CascadeType;
import javax.persistence.JoinColumns;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;


// https://qiita.com/kuinaein/items/5387bdee8539da315a0f
import lombok.Data;

import com.exsample.entity.RefTable;
import com.exsample.entity.MainTableId;

/**
 * MainTable generated by hbm2java
 */
@Entity
@Table(name="MainTable")
@IdClass(MainTableId.class)
public class MainTable implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;
	@Id
	@Column(columnDefinition = "int default 1")
	private Long subId;

    @OneToMany(orphanRemoval = true, fetch = FetchType.EAGER,  cascade = CascadeType.ALL)
    @Fetch(value = FetchMode.SUBSELECT)
    @JoinColumns ({
        @JoinColumn(name="id", referencedColumnName = "id"),
        @JoinColumn(name="subId", referencedColumnName = "subId")
    })
    private List<RefTable> refTables;
    
	private String str1;
	private String str2;
	private String str3;
	private String str4;
	private String str5;
	private BigDecimal num1;
	private BigDecimal num2;
	private BigDecimal num3;
	private BigDecimal num4;
	private BigDecimal num5;
	private Date updateTime;

	public MainTable() {
		this.subId = new Long(1);
	}

	public MainTable(Long id, Long subId) {
		this.id = id;
		this.subId = subId;
	}

	public MainTable(Long id, Long subId, String str1, String str2, String str3, String str4, String str5,
			BigDecimal num1, BigDecimal num2, BigDecimal num3, BigDecimal num4, BigDecimal num5, Date updateTime) {
		this.id = id;
		this.subId = subId;
		this.str1 = str1;
		this.str2 = str2;
		this.str3 = str3;
		this.str4 = str4;
		this.str5 = str5;
		this.num1 = num1;
		this.num2 = num2;
		this.num3 = num3;
		this.num4 = num4;
		this.num5 = num5;
		this.updateTime = updateTime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getSubId() {
		return this.subId;
	}

	public void setSubId(Long subId) {
		this.subId = subId;
	}
	
	public List<RefTable> getRefTables() {
		return this.refTables;
	}

	public void setRefTables(List<RefTable> refTables) {
		this.refTables = refTables;
	}

	public String getStr1() {
		return this.str1;
	}

	public void setStr1(String str1) {
		this.str1 = str1;
	}

	public String getStr2() {
		return this.str2;
	}

	public void setStr2(String str2) {
		this.str2 = str2;
	}

	public String getStr3() {
		return this.str3;
	}

	public void setStr3(String str3) {
		this.str3 = str3;
	}

	public String getStr4() {
		return this.str4;
	}

	public void setStr4(String str4) {
		this.str4 = str4;
	}

	public String getStr5() {
		return this.str5;
	}

	public void setStr5(String str5) {
		this.str5 = str5;
	}

	public BigDecimal getNum1() {
		return this.num1;
	}

	public void setNum1(BigDecimal num1) {
		this.num1 = num1;
	}

	public BigDecimal getNum2() {
		return this.num2;
	}

	public void setNum2(BigDecimal num2) {
		this.num2 = num2;
	}

	public BigDecimal getNum3() {
		return this.num3;
	}

	public void setNum3(BigDecimal num3) {
		this.num3 = num3;
	}

	public BigDecimal getNum4() {
		return this.num4;
	}

	public void setNum4(BigDecimal num4) {
		this.num4 = num4;
	}

	public BigDecimal getNum5() {
		return this.num5;
	}

	public void setNum5(BigDecimal num5) {
		this.num5 = num5;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

    public void addRefTable(RefTable refTable) {

        if (refTables == null ){
        	refTables = new ArrayList<RefTable>();
        }

        if (!refTables.contains(refTable))  {
        	refTables.add(refTable);
        }
    }
}
