package com.exsample.entity;
// Generated 2019/10/14 14:23:33 by Hibernate Tools 5.4.3.Final

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Id;
/**
 * MainTableId generated by hbm2java
 */
@Embeddable
public class MainTableId implements java.io.Serializable {

	private Long id;
	private Long subId;

	public MainTableId() {
	}

	public MainTableId(Long id, Long subId) {
		this.id = id;
		this.subId = subId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getSubId() {
		return this.subId;
	}

	public void setSubId(Long subId) {
		this.subId = subId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MainTableId))
			return false;
		MainTableId castOther = (MainTableId) other;

		return (this.getId() == castOther.getId()) && (this.getSubId() == castOther.getSubId());
	}

	public int hashCode() {
		int hsCode;
		
	    hsCode = id.hashCode();
	    hsCode = 19 * hsCode+ subId.hashCode();
	    return hsCode;
	}

}
