package com.exsample.entity;
import javax.persistence.Column;
// Generated 2019/10/14 14:23:33 by Hibernate Tools 5.4.3.Final
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * RefTableId generated by hbm2java
 */
@Embeddable
public class RefTableId implements java.io.Serializable {

	private Long refId;
	private Long refSubId;

	public RefTableId() {
	}

	public RefTableId(Long refId, Long refSubId) {
		this.refId = refId;
		this.refSubId = refSubId;
	}

	public Long getRefId() {
		return this.refId;
	}

	public void setRefId(Long refId) {
		this.refId = refId;
	}

	public Long getRefSubId() {
		return this.refSubId;
	}

	public void setRefSubId(Long refSubId) {
		this.refSubId = refSubId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RefTableId))
			return false;
		RefTableId castOther = (RefTableId) other;

		return (this.getRefId() == castOther.getRefId()) && (this.getRefSubId() == castOther.getRefSubId());
	}

	public int hashCode() {
		int hsCode;
	    hsCode = refId.hashCode();
	    hsCode = 19 * hsCode+ refSubId.hashCode();
	    return hsCode;
	}

}
